In [89]:
import numpy as np
arr = np.array([0,1,2,3,4,5,6])
pr = np.array([[0,2.0,2.5,3.8,4.8,5.8,6.3],
    [0,2.1,2.9,3.6,4.7,5.4,6.5],
    [0,1.7,2.4,3.7,4.4,5.7,6.6],
    [0,1.9,2.3,3.6,4.3,5.9,6.4]])
sr = np.zeros((7,4))
ma = np.zeros(7)

In [90]:
print(ma)
for i in range(len(pr)):
    for j in range(len(pr[i])):
        sr[j][i] = pr[i][j]
print(sr)
sr.sort()
print(sr)
for i in range(len(sr)):
    ma[i]=sr[i][3]
print(ma)
for i in range(len(sr)):
    if ma[i]<(sr[i-1][3]+sr[i-1][2]):
        print(sr[i-1][3]+sr[i-1][2])
# for i in range(len(pr)):
#     if pr[i][1]> ma[1][:
#         ma[1] = pr[i][1]
# print(ma)
# for i in range(len(pr)):
#     if pr[i][2] > ma[2]:
#         ma[2] = pr[i][2]

[0. 0. 0. 0. 0. 0. 0.]
[[0.  0.  0.  0. ]
 [2.  2.1 1.7 1.9]
 [2.5 2.9 2.4 2.3]
 [3.8 3.6 3.7 3.6]
 [4.8 4.7 4.4 4.3]
 [5.8 5.4 5.7 5.9]
 [6.3 6.5 6.6 6.4]]
[[0.  0.  0.  0. ]
 [1.7 1.9 2.  2.1]
 [2.3 2.4 2.5 2.9]
 [3.6 3.6 3.7 3.8]
 [4.3 4.4 4.7 4.8]
 [5.4 5.7 5.8 5.9]
 [6.3 6.4 6.5 6.6]]
[0.  2.1 2.9 3.8 4.8 5.9 6.6]
13.1
4.1
5.4
7.5
9.5
11.7
